// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

///Area conversion functions
pub mod area {
	/// Acres conversion functions
	pub mod acres {
		/// Converts the supplied Acres value to Square Kilometres
		/// # Arguments
		/// * `value` - The Acres input value
		pub fn to_square_kilometres(value: f64) -> f64 {
			return value / 247.105;
		}
		/// Converts the supplied Acres value to Square Metres
		/// # Arguments
		/// * `value` - The Acres input value
		pub fn to_square_metres(value: f64) -> f64 {
			return value * 4046.86;
		}
		/// Converts the supplied Acres value to Square Miles
		/// # Arguments
		/// * `value` - The Acres input value
		pub fn to_square_miles(value: f64) -> f64 {
			return value / 640.0;
		}
		/// Converts the supplied Acres value to Square Yards
		/// # Arguments
		/// * `value` - The Acres input value
		pub fn to_square_yards(value: f64) -> f64 {
			return value * 4840.0;
		}
		/// Converts the supplied Acres value to Square Feet
		/// # Arguments
		/// * `value` - The Acres input value
		pub fn to_square_feet(value: f64) -> f64 {
			return value * 43560.0;
		}
		/// Converts the supplied Acres value to Square Inches
		/// # Arguments
		/// * `value` - The Acres input value
		pub fn to_square_inches(value: f64) -> f64 {
			return value * 6272640.0;
		}
		/// Converts the supplied Acres value to Hectares
		/// # Arguments
		/// * `value` - The Acres input value
		pub fn to_hectares(value: f64) -> f64 {
			return value / 2.471;
		}
	}
	/// Hectares conversion functions
	pub mod hectares {
		/// Converts the supplied Hectares value to Square Kilometres
		/// # Arguments
		/// * `value` - The Hectares input value
		pub fn to_square_kilometres(value: f64) -> f64 {
			return value / 100.0;
		}
		/// Converts the supplied Hectares value to Square Metres
		/// # Arguments
		/// * `value` - The Hectares input value
		pub fn to_square_metres(value: f64) -> f64 {
			return value * 10000.0;
		}
		/// Converts the supplied Hectares value to Square Miles
		/// # Arguments
		/// * `value` - The Hectares input value
		pub fn to_square_miles(value: f64) -> f64 {
			return value / 259.0;
		}
		/// Converts the supplied Hectares value to Square Yards
		/// # Arguments
		/// * `value` - The Hectares input value
		pub fn to_square_yards(value: f64) -> f64 {
			return value * 11959.900463011;
		}
		/// Converts the supplied Hectares value to Square Feet
		/// # Arguments
		/// * `value` - The Hectares input value
		pub fn to_square_feet(value: f64) -> f64 {
			return value * 107639.0;
		}
		/// Converts the supplied Hectares value to Square Inches
		/// # Arguments
		/// * `value` - The Hectares input value
		pub fn to_square_inches(value: f64) -> f64 {
			return value * 15500031.0;
		}
		/// Converts the supplied Hectares value to Acres
		/// # Arguments
		/// * `value` - The Hectares input value
		pub fn to_acres(value: f64) -> f64 {
			return value * 2.471;
		}
	}
	/// Square Feet conversion functions
	pub mod square_feet {
		/// Converts the supplied Square Feet value to Square Kilometres
		/// # Arguments
		/// * `value` - The Square Feet input value
		pub fn to_square_kilometres(value: f64) -> f64 {
			return value / 10763910.41671;
		}
		/// Converts the supplied Square Feet value to Square Metres
		/// # Arguments
		/// * `value` - The Square Feet input value
		pub fn to_square_metres(value: f64) -> f64 {
			return value / 10.764;
		}
		/// Converts the supplied Square Feet value to Square Miles
		/// # Arguments
		/// * `value` - The Square Feet input value
		pub fn to_square_miles(value: f64) -> f64 {
			return value / 27878400.0;
		}
		/// Converts the supplied Square Feet value to Square Yards
		/// # Arguments
		/// * `value` - The Square Feet input value
		pub fn to_square_yards(value: f64) -> f64 {
			return value / 9.0;
		}
		/// Converts the supplied Square Feet value to Square Inches
		/// # Arguments
		/// * `value` - The Square Feet input value
		pub fn to_square_inches(value: f64) -> f64 {
			return value * 144.0;
		}
		/// Converts the supplied Square Feet value to Hectares
		/// # Arguments
		/// * `value` - The Square Feet input value
		pub fn to_hectares(value: f64) -> f64 {
			return value / 107639.0;
		}
		/// Converts the supplied Square Feet value to Acres
		/// # Arguments
		/// * `value` - The Square Feet input value
		pub fn to_acres(value: f64) -> f64 {
			return value / 43560.0;
		}
	}
	/// Square Inches conversion functions
	pub mod square_inches {
		/// Converts the supplied Square Inches value to Square Kilometres
		/// # Arguments
		/// * `value` - The Square Inches input value
		pub fn to_square_kilometres(value: f64) -> f64 {
			return value / 1550003100.00;
		}
		/// Converts the supplied Square Inches value to Square Metres
		/// # Arguments
		/// * `value` - The Square Inches input value
		pub fn to_square_metres(value: f64) -> f64 {
			return value / 1550.0;
		}
		/// Converts the supplied Square Inches value to Square Miles
		/// # Arguments
		/// * `value` - The Square Inches input value
		pub fn to_square_miles(value: f64) -> f64 {
			return value / 4014489600.0;
		}
		/// Converts the supplied Square Inches value to Square Yards
		/// # Arguments
		/// * `value` - The Square Inches input value
		pub fn to_square_yards(value: f64) -> f64 {
			return value / 1296.0;
		}
		/// Converts the supplied Square Inches value to Square Feet
		/// # Arguments
		/// * `value` - The Square Inches input value
		pub fn to_square_feet(value: f64) -> f64 {
			return value / 144.0;
		}
		/// Converts the supplied Square Inches value to Hectares
		/// # Arguments
		/// * `value` - The Square Inches input value
		pub fn to_hectares(value: f64) -> f64 {
			return value / 15500031.0;
		}
		/// Converts the supplied Square Inches value to Acres
		/// # Arguments
		/// * `value` - The Square Inches input value
		pub fn to_acres(value: f64) -> f64 {
			return value / 6272640.0;
		}
	}
	/// Square Kilometres conversion functions
	pub mod square_kilometres {
		/// Converts the supplied Square Kilometres value to Square Metres
		/// # Arguments
		/// * `value` - The Square Kilometres input value
		pub fn to_square_metres(value: f64) -> f64 {
			return value * 1e+6;
		}
		/// Converts the supplied Square Kilometres value to Square Miles
		/// # Arguments
		/// * `value` - The Square Kilometres input value
		pub fn to_square_miles(value: f64) -> f64 {
			return value / 2.58999;
		}
		/// Converts the supplied Square Kilometres value to Square Yards
		/// # Arguments
		/// * `value` - The Square Kilometres input value
		pub fn to_square_yards(value: f64) -> f64 {
			return value * 1195990.05;
		}
		/// Converts the supplied Square Kilometres value to Square Feet
		/// # Arguments
		/// * `value` - The Square Kilometres input value
		pub fn to_square_feet(value: f64) -> f64 {
			return value * 10763910.41671;
		}
		/// Converts the supplied Square Kilometres value to Square Inches
		/// # Arguments
		/// * `value` - The Square Kilometres input value
		pub fn to_square_inches(value: f64) -> f64 {
			return value * 1550003100.00;
		}
		/// Converts the supplied Square Kilometres value to Hectares
		/// # Arguments
		/// * `value` - The Square Kilometres input value
		pub fn to_hectares(value: f64) -> f64 {
			return value * 100.0;
		}
		/// Converts the supplied Square Kilometres value to Acres
		/// # Arguments
		/// * `value` - The Square Kilometres input value
		pub fn to_acres(value: f64) -> f64 {
			return value * 247.105;
		}
	}
	/// Square Metres conversion functions
	pub mod square_metres {
		/// Converts the supplied Square Metres value to Square Kilometres
		/// # Arguments
		/// * `value` - The Square Metres input value
		pub fn to_square_kilometres(value: f64) -> f64 {
			return value / 1e+6;
		}
		/// Converts the supplied Square Metres value to Square Miles
		/// # Arguments
		/// * `value` - The Square Metres input value
		pub fn to_square_miles(value: f64) -> f64 {
			return value / 2589988.10;
		}
		/// Converts the supplied Square Metres value to Square Yards
		/// # Arguments
		/// * `value` - The Square Metres input value
		pub fn to_square_yards(value: f64) -> f64 {
			return value * 1.196;
		}
		/// Converts the supplied Square Metres value to Square Feet
		/// # Arguments
		/// * `value` - The Square Metres input value
		pub fn to_square_feet(value: f64) -> f64 {
			return value * 10.764;
		}
		/// Converts the supplied Square Metres value to Square Inches
		/// # Arguments
		/// * `value` - The Square Metres input value
		pub fn to_square_inches(value: f64) -> f64 {
			return value * 1550.0;
		}
		/// Converts the supplied Square Metres value to Hectares
		/// # Arguments
		/// * `value` - The Square Metres input value
		pub fn to_hectares(value: f64) -> f64 {
			return value / 10000.0;
		}
		/// Converts the supplied Square Metres value to Acres
		/// # Arguments
		/// * `value` - The Square Metres input value
		pub fn to_acres(value: f64) -> f64 {
			return value / 4046.86;
		}
	}
	/// Square Miles conversion functions
	pub mod square_miles {
		/// Converts the supplied Square Miles value to Square Kilometres
		/// # Arguments
		/// * `value` - The Square Miles input value
		pub fn to_square_kilometres(value: f64) -> f64 {
			return value * 2.58999;
		}
		/// Converts the supplied Square Miles value to Square Metres
		/// # Arguments
		/// * `value` - The Square Miles input value
		pub fn to_square_metres(value: f64) -> f64 {
			return value * 2589988.10;
		}
		/// Converts the supplied Square Miles value to Square Yards
		/// # Arguments
		/// * `value` - The Square Miles input value
		pub fn to_square_yards(value: f64) -> f64 {
			return value * 3097600.0;
		}
		/// Converts the supplied Square Miles value to Square Feet
		/// # Arguments
		/// * `value` - The Square Miles input value
		pub fn to_square_feet(value: f64) -> f64 {
			return value * 27878400.0;
		}
		/// Converts the supplied Square Miles value to Square Inches
		/// # Arguments
		/// * `value` - The Square Miles input value
		pub fn to_square_inches(value: f64) -> f64 {
			return value * 4014489600.0;
		}
		/// Converts the supplied Square Miles value to Hectares
		/// # Arguments
		/// * `value` - The Square Miles input value
		pub fn to_hectares(value: f64) -> f64 {
			return value * 259.0;
		}
		/// Converts the supplied Square Miles value to Acres
		/// # Arguments
		/// * `value` - The Square Miles input value
		pub fn to_acres(value: f64) -> f64 {
			return value * 640.0;
		}
	}
	/// Square Yards conversion functions
	pub mod square_yards {
		/// Converts the supplied Square Yards value to Square Kilometres
		/// # Arguments
		/// * `value` - The Square Yards input value
		pub fn to_square_kilometres(value: f64) -> f64 {
			return value / 1195990.05;
		}
		/// Converts the supplied Square Yards value to Square Metres
		/// # Arguments
		/// * `value` - The Square Yards input value
		pub fn to_square_metres(value: f64) -> f64 {
			return value / 1.196;
		}
		/// Converts the supplied Square Yards value to Square Miles
		/// # Arguments
		/// * `value` - The Square Yards input value
		pub fn to_square_miles(value: f64) -> f64 {
			return value / 3097600.0;
		}
		/// Converts the supplied Square Yards value to Square Feet
		/// # Arguments
		/// * `value` - The Square Yards input value
		pub fn to_square_feet(value: f64) -> f64 {
			return value * 9.0;
		}
		/// Converts the supplied Square Yards value to Square Inches
		/// # Arguments
		/// * `value` - The Square Yards input value
		pub fn to_square_inches(value: f64) -> f64 {
			return value * 1296.0;
		}
		/// Converts the supplied Square Yards value to Hectares
		/// # Arguments
		/// * `value` - The Square Yards input value
		pub fn to_hectares(value: f64) -> f64 {
			return value / 11959.900463011;
		}
		/// Converts the supplied Square Yards value to Acres
		/// # Arguments
		/// * `value` - The Square Yards input value
		pub fn to_acres(value: f64) -> f64 {
			return value / 4840.0;
		}
	}
}
