// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

//! # Force based converters

/// Dynes conversion functions
pub mod dynes {
	/// Converts the supplied Dynes value to Newtons
	/// # Arguments
	/// * `value` - The Dynes input value
	pub fn to_newtons(value: f64) -> f64 {
		return value / 100000.0;
	}
	/// Converts the supplied Dynes value to Poundals
	/// # Arguments
	/// * `value` - The Dynes input value
	pub fn to_poundals(value: f64) -> f64 {
		return value / 13825.4954376;
	}
	/// Converts the supplied Dynes value to Kilogram-force
	/// # Arguments
	/// * `value` - The Dynes input value
	pub fn to_kilogramforce(value: f64) -> f64 {
		return value / 980665.0;
	}
}
/// Kilogram-force conversion functions
pub mod kilogramforce {
	/// Converts the supplied Kilogram-force value to Newtons
	/// # Arguments
	/// * `value` - The Kilogram-force input value
	pub fn to_newtons(value: f64) -> f64 {
		return value * 9.80665;
	}
	/// Converts the supplied Kilogram-force value to Dynes
	/// # Arguments
	/// * `value` - The Kilogram-force input value
	pub fn to_dynes(value: f64) -> f64 {
		return value * 980665.0;
	}
	/// Converts the supplied Kilogram-force value to Poundals
	/// # Arguments
	/// * `value` - The Kilogram-force input value
	pub fn to_poundals(value: f64) -> f64 {
		return value * 70.93163528397;
	}
}
/// Newtons conversion functions
pub mod newtons {
	/// Converts the supplied Newtons value to Dynes
	/// # Arguments
	/// * `value` - The Newtons input value
	pub fn to_dynes(value: f64) -> f64 {
		return value * 100000.0;
	}
	/// Converts the supplied Newtons value to Poundals
	/// # Arguments
	/// * `value` - The Newtons input value
	pub fn to_poundals(value: f64) -> f64 {
		return value * 7.23301;
	}
	/// Converts the supplied Newtons value to Kilogram-force
	/// # Arguments
	/// * `value` - The Newtons input value
	pub fn to_kilogramforce(value: f64) -> f64 {
		return value / 9.80665;
	}
}
/// Poundals conversion functions
pub mod poundals {
	/// Converts the supplied Poundals value to Newtons
	/// # Arguments
	/// * `value` - The Poundals input value
	pub fn to_newtons(value: f64) -> f64 {
		return value / 7.23301;
	}
	/// Converts the supplied Poundals value to Dynes
	/// # Arguments
	/// * `value` - The Poundals input value
	pub fn to_dynes(value: f64) -> f64 {
		return value * 13825.4954376;
	}
	/// Converts the supplied Poundals value to Kilogram-force
	/// # Arguments
	/// * `value` - The Poundals input value
	pub fn to_kilogramforce(value: f64) -> f64 {
		return value / 70.93163528397;
	}
}
