// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

/// Fuel Economy conversion functions
pub mod fuel_economy {
	/// Kilometre Per Litre conversion functions
	pub mod kilometre_per_litre {
		/// Converts the supplied Kilometre Per Litre value to US Miles Per Gallon
		/// # Arguments
		/// * `value` - The Kilometre Per Litre input value
		pub fn to_u_s_miles_per_gallon(value: f64) -> f64 {
			return value * 2.35215;
		}
		/// Converts the supplied Kilometre Per Litre value to Miles Per Gallon
		/// # Arguments
		/// * `value` - The Kilometre Per Litre input value
		pub fn to_miles_per_gallon(value: f64) -> f64 {
			return value * 2.82481;
		}
	}
	/// Miles Per Gallon conversion functions
	pub mod miles_per_gallon {
		/// Converts the supplied Miles Per Gallon value to Kilometre Per Litre
		/// # Arguments
		/// * `value` - The Miles Per Gallon input value
		pub fn to_kilometre_per_litre(value: f64) -> f64 {
			return value / 2.82481;
		}
		/// Converts the supplied Miles Per Gallon value to US Miles Per Gallon
		/// # Arguments
		/// * `value` - The Miles Per Gallon input value
		pub fn to_u_s_miles_per_gallon(value: f64) -> f64 {
			return value / 1.20095;
		}
	}
	/// US Miles Per Gallon conversion functions
	pub mod u_s_miles_per_gallon {
		/// Converts the supplied US Miles Per Gallon value to Kilometre Per Litre
		/// # Arguments
		/// * `value` - The US Miles Per Gallon input value
		pub fn to_kilometre_per_litre(value: f64) -> f64 {
			return value / 2.35215;
		}
		/// Converts the supplied US Miles Per Gallon value to Miles Per Gallon
		/// # Arguments
		/// * `value` - The US Miles Per Gallon input value
		pub fn to_miles_per_gallon(value: f64) -> f64 {
			return value * 1.20095;
		}
	}
}

#[cfg(test)]
mod tests {
	use super::*;
	use assert_approx_eq::assert_approx_eq;

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownkilometre_per_litre_to_u_s_miles_per_gallon_1() {
		let result: f64 = fuel_economy::kilometre_per_litre::to_u_s_miles_per_gallon(109.0);
		assert_approx_eq!(256.384, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownkilometre_per_litre_to_u_s_miles_per_gallon_2() {
		let result: f64 = fuel_economy::kilometre_per_litre::to_u_s_miles_per_gallon(9.4);
		assert_approx_eq!(22.1102, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownkilometre_per_litre_to_u_s_miles_per_gallon_3() {
		let result: f64 = fuel_economy::kilometre_per_litre::to_u_s_miles_per_gallon(1.3);
		assert_approx_eq!(3.05779, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownkilometre_per_litre_to_miles_per_gallon_1() {
		let result: f64 = fuel_economy::kilometre_per_litre::to_miles_per_gallon(5.0);
		assert_approx_eq!(14.124, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownkilometre_per_litre_to_miles_per_gallon_2() {
		let result: f64 = fuel_economy::kilometre_per_litre::to_miles_per_gallon(180.0);
		assert_approx_eq!(508.466, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownkilometre_per_litre_to_miles_per_gallon_3() {
		let result: f64 = fuel_economy::kilometre_per_litre::to_miles_per_gallon(5.4);
		assert_approx_eq!(15.254, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownmiles_per_gallon_to_kilometre_per_litre_1() {
		let result: f64 = fuel_economy::miles_per_gallon::to_kilometre_per_litre(12.0);
		assert_approx_eq!(4.24807, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownmiles_per_gallon_to_kilometre_per_litre_2() {
		let result: f64 = fuel_economy::miles_per_gallon::to_kilometre_per_litre(8.2);
		assert_approx_eq!(2.90285, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownmiles_per_gallon_to_kilometre_per_litre_3() {
		let result: f64 = fuel_economy::miles_per_gallon::to_kilometre_per_litre(0.5);
		assert_approx_eq!(0.177003, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownmiles_per_gallon_to_u_s_miles_per_gallon_1() {
		let result: f64 = fuel_economy::miles_per_gallon::to_u_s_miles_per_gallon(1.4);
		assert_approx_eq!(1.16574, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownmiles_per_gallon_to_u_s_miles_per_gallon_2() {
		let result: f64 = fuel_economy::miles_per_gallon::to_u_s_miles_per_gallon(709.0);
		assert_approx_eq!(590.36575, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownmiles_per_gallon_to_u_s_miles_per_gallon_3() {
		let result: f64 = fuel_economy::miles_per_gallon::to_u_s_miles_per_gallon(0.9);
		assert_approx_eq!(0.74941, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownu_s_miles_per_gallon_to_kilometre_per_litre_1() {
		let result: f64 = fuel_economy::u_s_miles_per_gallon::to_kilometre_per_litre(23.0);
		assert_approx_eq!(9.77831, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownu_s_miles_per_gallon_to_kilometre_per_litre_2() {
		let result: f64 = fuel_economy::u_s_miles_per_gallon::to_kilometre_per_litre(7.0);
		assert_approx_eq!(2.97601, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownu_s_miles_per_gallon_to_kilometre_per_litre_3() {
		let result: f64 = fuel_economy::u_s_miles_per_gallon::to_kilometre_per_litre(0.9);
		assert_approx_eq!(0.382629, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownu_s_miles_per_gallon_to_miles_per_gallon_1() {
		let result: f64 = fuel_economy::u_s_miles_per_gallon::to_miles_per_gallon(109.0);
		assert_approx_eq!(130.9036, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownu_s_miles_per_gallon_to_miles_per_gallon_2() {
		let result: f64 = fuel_economy::u_s_miles_per_gallon::to_miles_per_gallon(78.2);
		assert_approx_eq!(93.91432, result, 0.01);
	}

	/// Need to convert to parameterized tests
	#[test]
	fn it_convert_knownu_s_miles_per_gallon_to_miles_per_gallon_3() {
		let result: f64 = fuel_economy::u_s_miles_per_gallon::to_miles_per_gallon(0.9);
		assert_approx_eq!(1.08086, result, 0.01);
	}

}
