// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

//! # Magnetomotive Force based converters

/// Ampere-turns conversion functions
pub mod ampereturns {
	/// Converts the supplied Ampere-turns value to Gilberts
	/// # Arguments
	/// * `value` - The Ampere-turns input value
	pub fn to_gilberts(value: f64) -> f64 {
		return value / 0.7957747154595;
	}
}
/// Gilberts conversion functions
pub mod gilberts {
	/// Converts the supplied Gilberts value to Ampere-turns
	/// # Arguments
	/// * `value` - The Gilberts input value
	pub fn to_ampereturns(value: f64) -> f64 {
		return value * 0.7957747154595;
	}
}
