// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

//! # Mass based converters

/// Carats conversion functions
pub mod carats {
	/// Converts the supplied Carats value to Milligrams
	/// # Arguments
	/// * `value` - The Carats input value
	pub fn to_milligrams(value: f64) -> f64 {
		return value * 200.0;
	}
	/// Converts the supplied Carats value to Grams
	/// # Arguments
	/// * `value` - The Carats input value
	pub fn to_grams(value: f64) -> f64 {
		return value / 5.0;
	}
	/// Converts the supplied Carats value to Kilograms
	/// # Arguments
	/// * `value` - The Carats input value
	pub fn to_kilograms(value: f64) -> f64 {
		return value / 5000.0;
	}
	/// Converts the supplied Carats value to Tonnes
	/// # Arguments
	/// * `value` - The Carats input value
	pub fn to_tonnes(value: f64) -> f64 {
		return value / 5e+6;
	}
	/// Converts the supplied Carats value to Ounces
	/// # Arguments
	/// * `value` - The Carats input value
	pub fn to_ounces(value: f64) -> f64 {
		return value * 0.00705479;
	}
	/// Converts the supplied Carats value to Pounds
	/// # Arguments
	/// * `value` - The Carats input value
	pub fn to_pounds(value: f64) -> f64 {
		return value * 0.000440925;
	}
	/// Converts the supplied Carats value to Stones
	/// # Arguments
	/// * `value` - The Carats input value
	pub fn to_stones(value: f64) -> f64 {
		return value * 3.1495e-5;
	}
}
/// Grams conversion functions
pub mod grams {
	/// Converts the supplied Grams value to Milligrams
	/// # Arguments
	/// * `value` - The Grams input value
	pub fn to_milligrams(value: f64) -> f64 {
		return value * 1000.0;
	}
	/// Converts the supplied Grams value to Kilograms
	/// # Arguments
	/// * `value` - The Grams input value
	pub fn to_kilograms(value: f64) -> f64 {
		return value / 1000.0;
	}
	/// Converts the supplied Grams value to Tonnes
	/// # Arguments
	/// * `value` - The Grams input value
	pub fn to_tonnes(value: f64) -> f64 {
		return value * 1e-6;
	}
	/// Converts the supplied Grams value to Ounces
	/// # Arguments
	/// * `value` - The Grams input value
	pub fn to_ounces(value: f64) -> f64 {
		return value / 28.3495231;
	}
	/// Converts the supplied Grams value to Pounds
	/// # Arguments
	/// * `value` - The Grams input value
	pub fn to_pounds(value: f64) -> f64 {
		return value / 453.59237;
	}
	/// Converts the supplied Grams value to Stones
	/// # Arguments
	/// * `value` - The Grams input value
	pub fn to_stones(value: f64) -> f64 {
		return value / 6350.29318;
	}
	/// Converts the supplied Grams value to Carats
	/// # Arguments
	/// * `value` - The Grams input value
	pub fn to_carats(value: f64) -> f64 {
		return value * 5.0;
	}
}
/// Kilograms conversion functions
pub mod kilograms {
	/// Converts the supplied Kilograms value to Milligrams
	/// # Arguments
	/// * `value` - The Kilograms input value
	pub fn to_milligrams(value: f64) -> f64 {
		return value * 1e+6;
	}
	/// Converts the supplied Kilograms value to Grams
	/// # Arguments
	/// * `value` - The Kilograms input value
	pub fn to_grams(value: f64) -> f64 {
		return value * 1000.0;
	}
	/// Converts the supplied Kilograms value to Tonnes
	/// # Arguments
	/// * `value` - The Kilograms input value
	pub fn to_tonnes(value: f64) -> f64 {
		return value * 0.001;
	}
	/// Converts the supplied Kilograms value to Ounces
	/// # Arguments
	/// * `value` - The Kilograms input value
	pub fn to_ounces(value: f64) -> f64 {
		return value * 35.274;
	}
	/// Converts the supplied Kilograms value to Pounds
	/// # Arguments
	/// * `value` - The Kilograms input value
	pub fn to_pounds(value: f64) -> f64 {
		return value * 2.20462;
	}
	/// Converts the supplied Kilograms value to Stones
	/// # Arguments
	/// * `value` - The Kilograms input value
	pub fn to_stones(value: f64) -> f64 {
		return value / 6.35029;
	}
	/// Converts the supplied Kilograms value to Carats
	/// # Arguments
	/// * `value` - The Kilograms input value
	pub fn to_carats(value: f64) -> f64 {
		return value * 5000.0;
	}
}
/// Milligrams conversion functions
pub mod milligrams {
	/// Converts the supplied Milligrams value to Grams
	/// # Arguments
	/// * `value` - The Milligrams input value
	pub fn to_grams(value: f64) -> f64 {
		return value / 1000.0;
	}
	/// Converts the supplied Milligrams value to Kilograms
	/// # Arguments
	/// * `value` - The Milligrams input value
	pub fn to_kilograms(value: f64) -> f64 {
		return value / 1e+6;
	}
	/// Converts the supplied Milligrams value to Tonnes
	/// # Arguments
	/// * `value` - The Milligrams input value
	pub fn to_tonnes(value: f64) -> f64 {
		return value / 1e+9;
	}
	/// Converts the supplied Milligrams value to Ounces
	/// # Arguments
	/// * `value` - The Milligrams input value
	pub fn to_ounces(value: f64) -> f64 {
		return value / 28349.5231;
	}
	/// Converts the supplied Milligrams value to Pounds
	/// # Arguments
	/// * `value` - The Milligrams input value
	pub fn to_pounds(value: f64) -> f64 {
		return value / 453592.37;
	}
	/// Converts the supplied Milligrams value to Stones
	/// # Arguments
	/// * `value` - The Milligrams input value
	pub fn to_stones(value: f64) -> f64 {
		return value / 6350293.18;
	}
	/// Converts the supplied Milligrams value to Carats
	/// # Arguments
	/// * `value` - The Milligrams input value
	pub fn to_carats(value: f64) -> f64 {
		return value / 200.0;
	}
}
/// Ounces conversion functions
pub mod ounces {
	/// Converts the supplied Ounces value to Milligrams
	/// # Arguments
	/// * `value` - The Ounces input value
	pub fn to_milligrams(value: f64) -> f64 {
		return value * 28349.5231;
	}
	/// Converts the supplied Ounces value to Grams
	/// # Arguments
	/// * `value` - The Ounces input value
	pub fn to_grams(value: f64) -> f64 {
		return value * 28.3495231;
	}
	/// Converts the supplied Ounces value to Kilograms
	/// # Arguments
	/// * `value` - The Ounces input value
	pub fn to_kilograms(value: f64) -> f64 {
		return value / 35.274;
	}
	/// Converts the supplied Ounces value to Tonnes
	/// # Arguments
	/// * `value` - The Ounces input value
	pub fn to_tonnes(value: f64) -> f64 {
		return value * 0.0000283495231;
	}
	/// Converts the supplied Ounces value to Pounds
	/// # Arguments
	/// * `value` - The Ounces input value
	pub fn to_pounds(value: f64) -> f64 {
		return value * 0.0625;
	}
	/// Converts the supplied Ounces value to Stones
	/// # Arguments
	/// * `value` - The Ounces input value
	pub fn to_stones(value: f64) -> f64 {
		return value / 224.0;
	}
	/// Converts the supplied Ounces value to Carats
	/// # Arguments
	/// * `value` - The Ounces input value
	pub fn to_carats(value: f64) -> f64 {
		return value / 0.00705479;
	}
}
/// Pounds conversion functions
pub mod pounds {
	/// Converts the supplied Pounds value to Milligrams
	/// # Arguments
	/// * `value` - The Pounds input value
	pub fn to_milligrams(value: f64) -> f64 {
		return value * 453592.37;
	}
	/// Converts the supplied Pounds value to Grams
	/// # Arguments
	/// * `value` - The Pounds input value
	pub fn to_grams(value: f64) -> f64 {
		return value * 453.59237;
	}
	/// Converts the supplied Pounds value to Kilograms
	/// # Arguments
	/// * `value` - The Pounds input value
	pub fn to_kilograms(value: f64) -> f64 {
		return value / 2.20462;
	}
	/// Converts the supplied Pounds value to Tonnes
	/// # Arguments
	/// * `value` - The Pounds input value
	pub fn to_tonnes(value: f64) -> f64 {
		return value / 2204.62;
	}
	/// Converts the supplied Pounds value to Ounces
	/// # Arguments
	/// * `value` - The Pounds input value
	pub fn to_ounces(value: f64) -> f64 {
		return value * 16.0;
	}
	/// Converts the supplied Pounds value to Stones
	/// # Arguments
	/// * `value` - The Pounds input value
	pub fn to_stones(value: f64) -> f64 {
		return value / 14.0;
	}
	/// Converts the supplied Pounds value to Carats
	/// # Arguments
	/// * `value` - The Pounds input value
	pub fn to_carats(value: f64) -> f64 {
		return value / 0.000440925;
	}
}
/// Stones conversion functions
pub mod stones {
	/// Converts the supplied Stones value to Milligrams
	/// # Arguments
	/// * `value` - The Stones input value
	pub fn to_milligrams(value: f64) -> f64 {
		return value * 6350293.18;
	}
	/// Converts the supplied Stones value to Grams
	/// # Arguments
	/// * `value` - The Stones input value
	pub fn to_grams(value: f64) -> f64 {
		return value * 6350.29318;
	}
	/// Converts the supplied Stones value to Kilograms
	/// # Arguments
	/// * `value` - The Stones input value
	pub fn to_kilograms(value: f64) -> f64 {
		return value * 6.35029;
	}
	/// Converts the supplied Stones value to Tonnes
	/// # Arguments
	/// * `value` - The Stones input value
	pub fn to_tonnes(value: f64) -> f64 {
		return value / 157.473;
	}
	/// Converts the supplied Stones value to Ounces
	/// # Arguments
	/// * `value` - The Stones input value
	pub fn to_ounces(value: f64) -> f64 {
		return value * 224.0;
	}
	/// Converts the supplied Stones value to Pounds
	/// # Arguments
	/// * `value` - The Stones input value
	pub fn to_pounds(value: f64) -> f64 {
		return value * 14.0;
	}
	/// Converts the supplied Stones value to Carats
	/// # Arguments
	/// * `value` - The Stones input value
	pub fn to_carats(value: f64) -> f64 {
		return value / 3.1495e-5;
	}
}
/// Tonnes conversion functions
pub mod tonnes {
	/// Converts the supplied Tonnes value to Milligrams
	/// # Arguments
	/// * `value` - The Tonnes input value
	pub fn to_milligrams(value: f64) -> f64 {
		return value * 1e+9;
	}
	/// Converts the supplied Tonnes value to Grams
	/// # Arguments
	/// * `value` - The Tonnes input value
	pub fn to_grams(value: f64) -> f64 {
		return value * 1e+6;
	}
	/// Converts the supplied Tonnes value to Kilograms
	/// # Arguments
	/// * `value` - The Tonnes input value
	pub fn to_kilograms(value: f64) -> f64 {
		return value * 1000.0;
	}
	/// Converts the supplied Tonnes value to Ounces
	/// # Arguments
	/// * `value` - The Tonnes input value
	pub fn to_ounces(value: f64) -> f64 {
		return value / 0.0000283495231;
	}
	/// Converts the supplied Tonnes value to Pounds
	/// # Arguments
	/// * `value` - The Tonnes input value
	pub fn to_pounds(value: f64) -> f64 {
		return value * 2204.62;
	}
	/// Converts the supplied Tonnes value to Stones
	/// # Arguments
	/// * `value` - The Tonnes input value
	pub fn to_stones(value: f64) -> f64 {
		return value * 157.473;
	}
	/// Converts the supplied Tonnes value to Carats
	/// # Arguments
	/// * `value` - The Tonnes input value
	pub fn to_carats(value: f64) -> f64 {
		return value * 5e+6;
	}
}
