// <auto-generated>
// This code was generated by the UnitCodeGenerator tool
//
// Changes to this file will be lost if the code is regenerated
// </auto-generated>

///Volume conversion functions
pub mod volume {
	/// Fluid Ounces conversion functions
	pub mod fluid_ounces {
		/// Converts the supplied Fluid Ounces value to Millilitres
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 28.413074243749994496;
		}
		/// Converts the supplied Fluid Ounces value to Litres
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 0.028413074243749994496;
		}
		/// Converts the supplied Fluid Ounces value to Kilolitres
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.000028413074243749994;
		}
		/// Converts the supplied Fluid Ounces value to Teaspoons
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 4.8;
		}
		/// Converts the supplied Fluid Ounces value to Tablespoons
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value * 1.6;
		}
		/// Converts the supplied Fluid Ounces value to Quarts
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_quarts(value: f64) -> f64 {
			return value / 40.0;
		}
		/// Converts the supplied Fluid Ounces value to Pints
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_pints(value: f64) -> f64 {
			return value / 20.0;
		}
		/// Converts the supplied Fluid Ounces value to Gallons
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_gallons(value: f64) -> f64 {
			return value / 160.0;
		}
		/// Converts the supplied Fluid Ounces value to US Teaspoons
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value / 0.1734737167638313984;
		}
		/// Converts the supplied Fluid Ounces value to US Tablespoons
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value / 0.52042115029149417472;
		}
		/// Converts the supplied Fluid Ounces value to US Quarts
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 33.306953618655629312;
		}
		/// Converts the supplied Fluid Ounces value to US Pints
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 16.653476809327814656;
		}
		/// Converts the supplied Fluid Ounces value to US Gallons
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 133.22781447462252544;
		}
		/// Converts the supplied Fluid Ounces value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value / 1.0408423005829883904;
		}
		/// Converts the supplied Fluid Ounces value to US Cups
		/// # Arguments
		/// * `value` - The Fluid Ounces input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 8.3267384046639071232;
		}
	}
	/// Gallons conversion functions
	pub mod gallons {
		/// Converts the supplied Gallons value to Millilitres
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 4546.091879;
		}
		/// Converts the supplied Gallons value to Litres
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 4.546091879;
		}
		/// Converts the supplied Gallons value to Kilolitres
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.0045460918799;
		}
		/// Converts the supplied Gallons value to Teaspoons
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 768.0;
		}
		/// Converts the supplied Gallons value to Tablespoons
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value * 256.0;
		}
		/// Converts the supplied Gallons value to Quarts
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_quarts(value: f64) -> f64 {
			return value * 4.0;
		}
		/// Converts the supplied Gallons value to Pints
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_pints(value: f64) -> f64 {
			return value * 8.0;
		}
		/// Converts the supplied Gallons value to Fluid Ounces
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value * 160.0;
		}
		/// Converts the supplied Gallons value to US Teaspoons
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value / 0.00108421072977394606;
		}
		/// Converts the supplied Gallons value to US Tablespoons
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value / 0.003252632189321838592;
		}
		/// Converts the supplied Gallons value to US Quarts
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 0.20816846011659767808;
		}
		/// Converts the supplied Gallons value to US Pints
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 0.10408423005829883904;
		}
		/// Converts the supplied Gallons value to US Gallons
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 0.83267384046639071232;
		}
		/// Converts the supplied Gallons value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value / 0.006505264378643677184;
		}
		/// Converts the supplied Gallons value to US Cups
		/// # Arguments
		/// * `value` - The Gallons input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 0.052042115029149417472;
		}
	}
	/// Kilolitres conversion functions
	pub mod kilolitres {
		/// Converts the supplied Kilolitres value to Millilitres
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 1000000.0;
		}
		/// Converts the supplied Kilolitres value to Litres
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 1000.0;
		}
		/// Converts the supplied Kilolitres value to Teaspoons
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value / 0.000005919390467447916;
		}
		/// Converts the supplied Kilolitres value to Tablespoons
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value / 0.000017758171402343747;
		}
		/// Converts the supplied Kilolitres value to Quarts
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_quarts(value: f64) -> f64 {
			return value / 0.00113652296975;
		}
		/// Converts the supplied Kilolitres value to Pints
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_pints(value: f64) -> f64 {
			return value / 0.000568261484874999889;
		}
		/// Converts the supplied Kilolitres value to Gallons
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_gallons(value: f64) -> f64 {
			return value / 0.0045460918799;
		}
		/// Converts the supplied Kilolitres value to Fluid Ounces
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value / 0.0000284130742437499946;
		}
		/// Converts the supplied Kilolitres value to US Teaspoons
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value / 0.000004928921593749999;
		}
		/// Converts the supplied Kilolitres value to US Tablespoons
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value / 0.000014786764781249998;
		}
		/// Converts the supplied Kilolitres value to US Quarts
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 0.000946352945999999959;
		}
		/// Converts the supplied Kilolitres value to US Pints
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 0.000473176472999999979;
		}
		/// Converts the supplied Kilolitres value to US Gallons
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 0.003785411784;
		}
		/// Converts the supplied Kilolitres value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value / 0.0000295735296;
		}
		/// Converts the supplied Kilolitres value to US Cups
		/// # Arguments
		/// * `value` - The Kilolitres input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 0.000236588236499999989;
		}
	}
	/// Litres conversion functions
	pub mod litres {
		/// Converts the supplied Litres value to Millilitres
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 1000.0;
		}
		/// Converts the supplied Litres value to Kilolitres
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value / 1000.0;
		}
		/// Converts the supplied Litres value to Teaspoons
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value / 0.005919390467447916134;
		}
		/// Converts the supplied Litres value to Tablespoons
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value / 0.017758171402343747584;
		}
		/// Converts the supplied Litres value to Quarts
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_quarts(value: f64) -> f64 {
			return value / 1.13652296975;
		}
		/// Converts the supplied Litres value to Pints
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_pints(value: f64) -> f64 {
			return value / 0.56826148487499988992;
		}
		/// Converts the supplied Litres value to Gallons
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_gallons(value: f64) -> f64 {
			return value / 4.546091879;
		}
		/// Converts the supplied Litres value to Fluid Ounces
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value / 0.028413074243749994496;
		}
		/// Converts the supplied Litres value to US Teaspoons
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value / 0.004928921593749999616;
		}
		/// Converts the supplied Litres value to US Tablespoons
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value / 0.014786764781249998848;
		}
		/// Converts the supplied Litres value to US Quarts
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 0.94635294599999995904;
		}
		/// Converts the supplied Litres value to US Pints
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 0.47317647299999997952;
		}
		/// Converts the supplied Litres value to US Gallons
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 3.785411784;
		}
		/// Converts the supplied Litres value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value / 0.029573529562499997696;
		}
		/// Converts the supplied Litres value to US Cups
		/// # Arguments
		/// * `value` - The Litres input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 0.23658823649999998976;
		}
	}
	/// Millilitres conversion functions
	pub mod millilitres {
		/// Converts the supplied Millilitres value to Litres
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_litres(value: f64) -> f64 {
			return value / 1000.0;
		}
		/// Converts the supplied Millilitres value to Kilolitres
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value / 1000000.0;
		}
		/// Converts the supplied Millilitres value to Teaspoons
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value / 5.9193904674479161344;
		}
		/// Converts the supplied Millilitres value to Tablespoons
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value / 17.758171402343747584;
		}
		/// Converts the supplied Millilitres value to Quarts
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_quarts(value: f64) -> f64 {
			return value / 1136.52296975;
		}
		/// Converts the supplied Millilitres value to Pints
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_pints(value: f64) -> f64 {
			return value / 568.26148487499988992;
		}
		/// Converts the supplied Millilitres value to Gallons
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_gallons(value: f64) -> f64 {
			return value / 4546.091879;
		}
		/// Converts the supplied Millilitres value to Fluid Ounces
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value / 28.413074243749994496;
		}
		/// Converts the supplied Millilitres value to US Teaspoons
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value / 4.928921593749999616;
		}
		/// Converts the supplied Millilitres value to US Tablespoons
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value / 14.786764781249998848;
		}
		/// Converts the supplied Millilitres value to US Quarts
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 946.35294599999995904;
		}
		/// Converts the supplied Millilitres value to US Pints
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 473.17647299999997952;
		}
		/// Converts the supplied Millilitres value to US Gallons
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 3785.411784;
		}
		/// Converts the supplied Millilitres value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value / 29.573529562499997696;
		}
		/// Converts the supplied Millilitres value to US Cups
		/// # Arguments
		/// * `value` - The Millilitres input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 236.58823649999998976;
		}
	}
	/// Pints conversion functions
	pub mod pints {
		/// Converts the supplied Pints value to Millilitres
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 568.26148487499988992;
		}
		/// Converts the supplied Pints value to Litres
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 0.56826148487499988992;
		}
		/// Converts the supplied Pints value to Kilolitres
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.000568261484874999889;
		}
		/// Converts the supplied Pints value to Teaspoons
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 96.0;
		}
		/// Converts the supplied Pints value to Tablespoons
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value * 32.0;
		}
		/// Converts the supplied Pints value to Quarts
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_quarts(value: f64) -> f64 {
			return value  / 2.0;
		}
		/// Converts the supplied Pints value to Gallons
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_gallons(value: f64) -> f64 {
			return value / 8.0;
		}
		/// Converts the supplied Pints value to Fluid Ounces
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value * 20.0;
		}
		/// Converts the supplied Pints value to US Teaspoons
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value / 0.008673685838191568486;
		}
		/// Converts the supplied Pints value to US Tablespoons
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value / 0.026021057514574708736;
		}
		/// Converts the supplied Pints value to US Quarts
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 1.6653476809327814656;
		}
		/// Converts the supplied Pints value to US Pints
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 0.83267384046639071232;
		}
		/// Converts the supplied Pints value to US Gallons
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 6.6613907237311258624;
		}
		/// Converts the supplied Pints value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value / 0.052042115029149417472;
		}
		/// Converts the supplied Pints value to US Cups
		/// # Arguments
		/// * `value` - The Pints input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 0.41633692023319535616;
		}
	}
	/// Quarts conversion functions
	pub mod quarts {
		/// Converts the supplied Quarts value to Millilitres
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 1136.52296975;
		}
		/// Converts the supplied Quarts value to Litres
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 1.13652296975;
		}
		/// Converts the supplied Quarts value to Kilolitres
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.00113652296975;
		}
		/// Converts the supplied Quarts value to Teaspoons
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 192.0;
		}
		/// Converts the supplied Quarts value to Tablespoons
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value * 64.0;
		}
		/// Converts the supplied Quarts value to Pints
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_pints(value: f64) -> f64 {
			return value * 2.0;
		}
		/// Converts the supplied Quarts value to Gallons
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_gallons(value: f64) -> f64 {
			return value / 4.0;
		}
		/// Converts the supplied Quarts value to Fluid Ounces
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value * 40.0;
		}
		/// Converts the supplied Quarts value to US Teaspoons
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value / 0.004336842919095784243;
		}
		/// Converts the supplied Quarts value to US Tablespoons
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value / 0.013010528757287354368;
		}
		/// Converts the supplied Quarts value to US Quarts
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 0.83267384046639071232;
		}
		/// Converts the supplied Quarts value to US Pints
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 0.41633692023319535616;
		}
		/// Converts the supplied Quarts value to US Gallons
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 3.3306953618655629312;
		}
		/// Converts the supplied Quarts value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value / 0.026021057514574708736;
		}
		/// Converts the supplied Quarts value to US Cups
		/// # Arguments
		/// * `value` - The Quarts input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 0.20816846011659767808;
		}
	}
	/// Tablespoons conversion functions
	pub mod tablespoons {
		/// Converts the supplied Tablespoons value to Millilitres
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 17.758171402343747584;
		}
		/// Converts the supplied Tablespoons value to Litres
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 0.017758171402343747584;
		}
		/// Converts the supplied Tablespoons value to Kilolitres
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.000017758171402343747;
		}
		/// Converts the supplied Tablespoons value to Teaspoons
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 3.0;
		}
		/// Converts the supplied Tablespoons value to Quarts
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_quarts(value: f64) -> f64 {
			return value / 64.0;
		}
		/// Converts the supplied Tablespoons value to Pints
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_pints(value: f64) -> f64 {
			return value / 32.0;
		}
		/// Converts the supplied Tablespoons value to Gallons
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_gallons(value: f64) -> f64 {
			return value / 256.0;
		}
		/// Converts the supplied Tablespoons value to Fluid Ounces
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value / 1.6;
		}
		/// Converts the supplied Tablespoons value to US Teaspoons
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value / 0.27755794682213023744;
		}
		/// Converts the supplied Tablespoons value to US Tablespoons
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value / 0.83267384046639071232;
		}
		/// Converts the supplied Tablespoons value to US Quarts
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 53.291125789849001984;
		}
		/// Converts the supplied Tablespoons value to US Pints
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 26.645562894924500992;
		}
		/// Converts the supplied Tablespoons value to US Gallons
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 213.16450315939602432;
		}
		/// Converts the supplied Tablespoons value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value / 1.6653476809327814656;
		}
		/// Converts the supplied Tablespoons value to US Cups
		/// # Arguments
		/// * `value` - The Tablespoons input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 13.322781447462250496;
		}
	}
	/// Teaspoons conversion functions
	pub mod teaspoons {
		/// Converts the supplied Teaspoons value to Millilitres
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 5.9193904674479161344;
		}
		/// Converts the supplied Teaspoons value to Litres
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 0.005919390467447916134;
		}
		/// Converts the supplied Teaspoons value to Kilolitres
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.000005919390467447916;
		}
		/// Converts the supplied Teaspoons value to Tablespoons
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value / 3.0;
		}
		/// Converts the supplied Teaspoons value to Quarts
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_quarts(value: f64) -> f64 {
			return value / 192.0;
		}
		/// Converts the supplied Teaspoons value to Pints
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_pints(value: f64) -> f64 {
			return value / 96.0;
		}
		/// Converts the supplied Teaspoons value to Gallons
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_gallons(value: f64) -> f64 {
			return value / 768.0;
		}
		/// Converts the supplied Teaspoons value to Fluid Ounces
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value / 4.8;
		}
		/// Converts the supplied Teaspoons value to US Teaspoons
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value / 0.83267384046639071232;
		}
		/// Converts the supplied Teaspoons value to US Tablespoons
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value / 2.4980215213991718912;
		}
		/// Converts the supplied Teaspoons value to US Quarts
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 159.87337736954701824;
		}
		/// Converts the supplied Teaspoons value to US Pints
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 79.936688684773507072;
		}
		/// Converts the supplied Teaspoons value to US Gallons
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 639.49350947818807296;
		}
		/// Converts the supplied Teaspoons value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value / 4.9960430427983437824;
		}
		/// Converts the supplied Teaspoons value to US Cups
		/// # Arguments
		/// * `value` - The Teaspoons input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 39.968344342386753536;
		}
	}
	/// US Cups conversion functions
	pub mod u_s_cups {
		/// Converts the supplied US Cups value to Millilitres
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 236.58823649999998976;
		}
		/// Converts the supplied US Cups value to Litres
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 0.23658823649999998976;
		}
		/// Converts the supplied US Cups value to Kilolitres
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.000236588236499999989;
		}
		/// Converts the supplied US Cups value to Teaspoons
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 39.968344342386753536;
		}
		/// Converts the supplied US Cups value to Tablespoons
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value * 13.322781447462250496;
		}
		/// Converts the supplied US Cups value to Quarts
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_quarts(value: f64) -> f64 {
			return value * 0.20816846011659767808;
		}
		/// Converts the supplied US Cups value to Pints
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_pints(value: f64) -> f64 {
			return value * 0.41633692023319535616;
		}
		/// Converts the supplied US Cups value to Gallons
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_gallons(value: f64) -> f64 {
			return value * 0.052042115029149417472;
		}
		/// Converts the supplied US Cups value to Fluid Ounces
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value * 8.3267384046639071232;
		}
		/// Converts the supplied US Cups value to US Teaspoons
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value * 48.0;
		}
		/// Converts the supplied US Cups value to US Tablespoons
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value * 16.0;
		}
		/// Converts the supplied US Cups value to US Quarts
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 4.0;
		}
		/// Converts the supplied US Cups value to US Pints
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 2.0;
		}
		/// Converts the supplied US Cups value to US Gallons
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 16.0;
		}
		/// Converts the supplied US Cups value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The US Cups input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value * 8.0;
		}
	}
	/// US Fluid Ounces conversion functions
	pub mod u_s_fluid_ounces {
		/// Converts the supplied US Fluid Ounces value to Millilitres
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 29.573529562499997696;
		}
		/// Converts the supplied US Fluid Ounces value to Litres
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 0.029573529562499997696;
		}
		/// Converts the supplied US Fluid Ounces value to Kilolitres
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.0000295735296;
		}
		/// Converts the supplied US Fluid Ounces value to Teaspoons
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 4.9960430427983437824;
		}
		/// Converts the supplied US Fluid Ounces value to Tablespoons
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value * 1.6653476809327814656;
		}
		/// Converts the supplied US Fluid Ounces value to Quarts
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_quarts(value: f64) -> f64 {
			return value * 0.026021057514574708736;
		}
		/// Converts the supplied US Fluid Ounces value to Pints
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_pints(value: f64) -> f64 {
			return value * 0.052042115029149417472;
		}
		/// Converts the supplied US Fluid Ounces value to Gallons
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_gallons(value: f64) -> f64 {
			return value * 0.006505264378643677184;
		}
		/// Converts the supplied US Fluid Ounces value to Fluid Ounces
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value * 1.0408423005829883904;
		}
		/// Converts the supplied US Fluid Ounces value to US Teaspoons
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value * 6.0;
		}
		/// Converts the supplied US Fluid Ounces value to US Tablespoons
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value * 2.0;
		}
		/// Converts the supplied US Fluid Ounces value to US Quarts
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 32.0;
		}
		/// Converts the supplied US Fluid Ounces value to US Pints
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 16.0;
		}
		/// Converts the supplied US Fluid Ounces value to US Gallons
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 128.0;
		}
		/// Converts the supplied US Fluid Ounces value to US Cups
		/// # Arguments
		/// * `value` - The US Fluid Ounces input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 8.0;
		}
	}
	/// US Gallons conversion functions
	pub mod u_s_gallons {
		/// Converts the supplied US Gallons value to Millilitres
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 3785.411784;
		}
		/// Converts the supplied US Gallons value to Litres
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 3.785411784;
		}
		/// Converts the supplied US Gallons value to Kilolitres
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.003785411784;
		}
		/// Converts the supplied US Gallons value to Teaspoons
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 639.49350947818807296;
		}
		/// Converts the supplied US Gallons value to Tablespoons
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value * 213.16450315939602432;
		}
		/// Converts the supplied US Gallons value to Quarts
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_quarts(value: f64) -> f64 {
			return value * 3.3306953618655629312;
		}
		/// Converts the supplied US Gallons value to Pints
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_pints(value: f64) -> f64 {
			return value * 6.6613907237311258624;
		}
		/// Converts the supplied US Gallons value to Gallons
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_gallons(value: f64) -> f64 {
			return value * 0.83267384046639071232;
		}
		/// Converts the supplied US Gallons value to Fluid Ounces
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value * 133.22781447462252544;
		}
		/// Converts the supplied US Gallons value to US Teaspoons
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value * 768.0;
		}
		/// Converts the supplied US Gallons value to US Tablespoons
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value * 256.0;
		}
		/// Converts the supplied US Gallons value to US Quarts
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value * 4.0;
		}
		/// Converts the supplied US Gallons value to US Pints
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value * 8.0;
		}
		/// Converts the supplied US Gallons value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value * 128.0;
		}
		/// Converts the supplied US Gallons value to US Cups
		/// # Arguments
		/// * `value` - The US Gallons input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value * 16.0;
		}
	}
	/// US Pints conversion functions
	pub mod u_s_pints {
		/// Converts the supplied US Pints value to Millilitres
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 473.17647299999997952;
		}
		/// Converts the supplied US Pints value to Litres
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 0.47317647299999997952;
		}
		/// Converts the supplied US Pints value to Kilolitres
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.000473176472999999979;
		}
		/// Converts the supplied US Pints value to Teaspoons
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 79.936688684773507072;
		}
		/// Converts the supplied US Pints value to Tablespoons
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value * 26.645562894924500992;
		}
		/// Converts the supplied US Pints value to Quarts
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_quarts(value: f64) -> f64 {
			return value * 0.41633692023319535616;
		}
		/// Converts the supplied US Pints value to Pints
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_pints(value: f64) -> f64 {
			return value * 0.83267384046639071232;
		}
		/// Converts the supplied US Pints value to Gallons
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_gallons(value: f64) -> f64 {
			return value * 0.10408423005829883904;
		}
		/// Converts the supplied US Pints value to Fluid Ounces
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value * 16.653476809327814656;
		}
		/// Converts the supplied US Pints value to US Teaspoons
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value * 96.0;
		}
		/// Converts the supplied US Pints value to US Tablespoons
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value * 32.0;
		}
		/// Converts the supplied US Pints value to US Quarts
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 2.0;
		}
		/// Converts the supplied US Pints value to US Gallons
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 8.0;
		}
		/// Converts the supplied US Pints value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value * 16.0;
		}
		/// Converts the supplied US Pints value to US Cups
		/// # Arguments
		/// * `value` - The US Pints input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value * 2.0;
		}
	}
	/// US Quarts conversion functions
	pub mod u_s_quarts {
		/// Converts the supplied US Quarts value to Millilitres
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 946.35294599999995904;
		}
		/// Converts the supplied US Quarts value to Litres
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 0.94635294599999995904;
		}
		/// Converts the supplied US Quarts value to Kilolitres
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.000946352945999999959;
		}
		/// Converts the supplied US Quarts value to Teaspoons
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 159.87337736954701824;
		}
		/// Converts the supplied US Quarts value to Tablespoons
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value * 53.291125789849001984;
		}
		/// Converts the supplied US Quarts value to Quarts
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_quarts(value: f64) -> f64 {
			return value * 0.83267384046639071232;
		}
		/// Converts the supplied US Quarts value to Pints
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_pints(value: f64) -> f64 {
			return value * 1.6653476809327814656;
		}
		/// Converts the supplied US Quarts value to Gallons
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_gallons(value: f64) -> f64 {
			return value * 0.20816846011659767808;
		}
		/// Converts the supplied US Quarts value to Fluid Ounces
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value * 33.306953618655629312;
		}
		/// Converts the supplied US Quarts value to US Teaspoons
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value * 192.0;
		}
		/// Converts the supplied US Quarts value to US Tablespoons
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value * 64.0;
		}
		/// Converts the supplied US Quarts value to US Pints
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value * 2.0;
		}
		/// Converts the supplied US Quarts value to US Gallons
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 4.0;
		}
		/// Converts the supplied US Quarts value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value * 32.0;
		}
		/// Converts the supplied US Quarts value to US Cups
		/// # Arguments
		/// * `value` - The US Quarts input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value * 4.0;
		}
	}
	/// US Tablespoons conversion functions
	pub mod u_s_tablespoons {
		/// Converts the supplied US Tablespoons value to Millilitres
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 14.786764781249998848;
		}
		/// Converts the supplied US Tablespoons value to Litres
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 0.014786764781249998848;
		}
		/// Converts the supplied US Tablespoons value to Kilolitres
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.000014786764781249998;
		}
		/// Converts the supplied US Tablespoons value to Teaspoons
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 2.4980215213991718912;
		}
		/// Converts the supplied US Tablespoons value to Tablespoons
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value * 0.83267384046639071232;
		}
		/// Converts the supplied US Tablespoons value to Quarts
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_quarts(value: f64) -> f64 {
			return value * 0.013010528757287354368;
		}
		/// Converts the supplied US Tablespoons value to Pints
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_pints(value: f64) -> f64 {
			return value * 0.026021057514574708736;
		}
		/// Converts the supplied US Tablespoons value to Gallons
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_gallons(value: f64) -> f64 {
			return value * 0.003252632189321838592;
		}
		/// Converts the supplied US Tablespoons value to Fluid Ounces
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value * 0.52042115029149417472;
		}
		/// Converts the supplied US Tablespoons value to US Teaspoons
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_u_s_teaspoons(value: f64) -> f64 {
			return value * 3.0;
		}
		/// Converts the supplied US Tablespoons value to US Quarts
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 64.0;
		}
		/// Converts the supplied US Tablespoons value to US Pints
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 32.0;
		}
		/// Converts the supplied US Tablespoons value to US Gallons
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 256.0;
		}
		/// Converts the supplied US Tablespoons value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value / 2.0;
		}
		/// Converts the supplied US Tablespoons value to US Cups
		/// # Arguments
		/// * `value` - The US Tablespoons input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 16.0;
		}
	}
	/// US Teaspoons conversion functions
	pub mod u_s_teaspoons {
		/// Converts the supplied US Teaspoons value to Millilitres
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_millilitres(value: f64) -> f64 {
			return value * 4.928921593749999616;
		}
		/// Converts the supplied US Teaspoons value to Litres
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_litres(value: f64) -> f64 {
			return value * 0.004928921593749999616;
		}
		/// Converts the supplied US Teaspoons value to Kilolitres
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_kilolitres(value: f64) -> f64 {
			return value * 0.000004928921593749999;
		}
		/// Converts the supplied US Teaspoons value to Teaspoons
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_teaspoons(value: f64) -> f64 {
			return value * 0.83267384046639071232;
		}
		/// Converts the supplied US Teaspoons value to Tablespoons
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_tablespoons(value: f64) -> f64 {
			return value * 0.27755794682213023744;
		}
		/// Converts the supplied US Teaspoons value to Quarts
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_quarts(value: f64) -> f64 {
			return value * 0.004336842919095784243;
		}
		/// Converts the supplied US Teaspoons value to Pints
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_pints(value: f64) -> f64 {
			return value * 0.008673685838191568486;
		}
		/// Converts the supplied US Teaspoons value to Gallons
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_gallons(value: f64) -> f64 {
			return value * 0.00108421072977394606;
		}
		/// Converts the supplied US Teaspoons value to Fluid Ounces
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_fluid_ounces(value: f64) -> f64 {
			return value * 0.1734737167638313984;
		}
		/// Converts the supplied US Teaspoons value to US Tablespoons
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_u_s_tablespoons(value: f64) -> f64 {
			return value / 3.0;
		}
		/// Converts the supplied US Teaspoons value to US Quarts
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_u_s_quarts(value: f64) -> f64 {
			return value / 192.0;
		}
		/// Converts the supplied US Teaspoons value to US Pints
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_u_s_pints(value: f64) -> f64 {
			return value / 96.0;
		}
		/// Converts the supplied US Teaspoons value to US Gallons
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_u_s_gallons(value: f64) -> f64 {
			return value / 768.0;
		}
		/// Converts the supplied US Teaspoons value to US Fluid Ounces
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_u_s_fluid_ounces(value: f64) -> f64 {
			return value / 6.0;
		}
		/// Converts the supplied US Teaspoons value to US Cups
		/// # Arguments
		/// * `value` - The US Teaspoons input value
		pub fn to_u_s_cups(value: f64) -> f64 {
			return value / 48.0;
		}
	}
}
