name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Manual Run

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

      # - uses: actions-rs/toolchain@v1
      #   with:
      #     toolchain: stable
      #     override: true
      # - uses: katyo/publish-crates@v1
      #   with:
      #     registry-token: ${{ secrets.CRATES_TOKEN }}      
      